services:
  app:
    build: .
    command: sh -c "npm run prisma:migrate && npm run prisma:generate && npm run build-dev"
    ports:
      - "4000:4000"
    volumes:
      - .:/app
    depends_on:
      - postgres

  postgres:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=shopper
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123456
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
